# Generated by Django 2.0.13 on 2019-03-28 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcartaofidelidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnderecoClientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(blank=True, max_length=80)),
                ('bairro', models.CharField(blank=True, max_length=50)),
                ('cidade', models.CharField(blank=True, max_length=50)),
                ('complemento', models.CharField(blank=True, max_length=70)),
                ('complemento2', models.CharField(max_length=70)),
                ('uf', models.CharField(blank=True, max_length=11)),
                ('cep', models.CharField(blank=True, max_length=13)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcartaofidelidade.Clientes')),
            ],
            options={
                'managed': True,
                'db_table': 'EnderecoClientes',
                'verbose_name': 'Endereco Cliente',
                'verbose_name_plural': 'Endereco Clientes',
            },
        ),
    ]
