# Generated by Django 2.0.13 on 2019-03-28 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcartaofidelidade', '0002_enderecoclientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecoclientes',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appcartaofidelidade.Clientes'),
        ),
    ]
