# Generated by Django 2.0.13 on 2019-03-28 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcartaofidelidade', '0003_auto_20190328_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecoclientes',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enderecoclientes',
            name='cep',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='enderecoclientes',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enderecoclientes',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='appcartaofidelidade.Clientes'),
        ),
        migrations.AlterField(
            model_name='enderecoclientes',
            name='complemento',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='enderecoclientes',
            name='complemento2',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='enderecoclientes',
            name='endereco',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='enderecoclientes',
            name='uf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
