# Generated by Django 2.0.13 on 2019-04-17 12:12

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appcartaofidelidade', '0004_auto_20190328_1314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empresas',
        ),
        migrations.RemoveField(
            model_name='enderecoclientes',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='registros',
            name='cartao',
        ),
        migrations.RemoveField(
            model_name='registros',
            name='servicos',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='empresas_idempresas',
        ),
        migrations.AddField(
            model_name='registros',
            name='servico',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='servicos',
            name='cod_servico',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='premios',
            name='cliente',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='premios',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='premios',
            name='servico',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registros',
            name='cliente',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registros',
            name='data',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='registros',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registros',
            name='status',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='EnderecoClientes',
        ),
    ]
