# Generated by Django 2.0.13 on 2019-04-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempresas', models.IntegerField(blank=True, db_column='idEmpresas', null=True)),
                ('nome', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'empresa',
                'db_table': 'Empresas',
                'managed': True,
                'verbose_name_plural': 'empresas',
            },
        ),
    ]
