# Generated by Django 2.0.13 on 2019-04-17 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('nome', models.CharField(max_length=80)),
                ('cpf', models.CharField(blank=True, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(blank=True, max_length=80, null=True)),
                ('cep', models.CharField(max_length=13)),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'clientes',
                'db_table': 'Clientes',
                'verbose_name': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='EnderecoClientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(blank=True, max_length=80, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('complemento', models.CharField(blank=True, max_length=70, null=True)),
                ('complemento2', models.CharField(max_length=70, null=True)),
                ('uf', models.CharField(blank=True, max_length=11, null=True)),
                ('cep', models.CharField(blank=True, max_length=13, null=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='cliente_service.Clientes')),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'Endereço Clientes',
                'db_table': 'EnderecoClientes',
                'verbose_name': 'Endereço Cliente',
            },
        ),
    ]
